repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: local
  hooks:
    - id: swiftlint
      name: swiftlint
      description: Check Swift style rules with Swiftlint.
      entry: swiftlint
      language: system
      files: \.swift$
      exclude: .*\/Carthage\/.*
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.3
  hooks:
    - id: clang-format
      files: \.(c|cc|cxx|cpp|h|hpp|hxx|m|mm)$
      exclude: .*\/Carthage\/.*
      args: ["-fallback-style=none", "-i"]
