name: Benchmarking
on:
  pull_request:
    paths:
      - 'Samples/iOS-Swift/iOS-Swift/ViewControllers/PerformanceViewController.swift'
      - 'Samples/iOS-Swift/PerformanceBenchmarks/**'
      - '.github/workflows/benchmarking.yml'
      - 'fastlane/**'

jobs:
  build-benchmark-test-target:
    name: Build UITests with Xcode
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/ci-select-xcode.sh
      - run: git apply ./scripts/set-device-tests-environment.patch
      - run: fastlane build_ios_benchmark_test
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
          FASTLANE_KEYCHAIN_PASSWORD: ${{ secrets.FASTLANE_KEYCHAIN_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
