name: lint
on:
  push:
    branches:
      - master
      - ci/xcbeautify
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'test-server/**'
      - 'Samples/**'

  pull_request:
    paths:
      - 'Sources/**'
      - 'Tests/**'
      - 'test-server/**'
      - 'Samples/**'

jobs:
  swift-lint:
    name: Swift Lint
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Run SwiftLint
        run: swiftlint

  xcode-analyze:
    name: Xcode Analyze
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/ci-select-xcode.sh
      - run: brew install xcbeautify
      - name: Run analyze
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild analyze -workspace Sentry.xcworkspace -scheme Sentry -configuration Release CLANG_ANALYZER_OUTPUT=html CLANG_ANALYZER_OUTPUT_DIR=analyzer | xcbeautify -t && [[ -z `find analyzer -name "*.html"` ]]

  validate-podspec:
    name: Validate Podspec
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Validate Podspec
        run: pod lib lint --verbose
        shell: sh

  validate-high-risk-files:
    name: No changes in high risk files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/no-changes-in-high-risk-files.sh
