# Defines a workflow that generates large volumes of real-ish profiling data to work with for various development tasks.

name: Generate Profiling Test Data
on:
  pull_request:
    paths:
      - '.github/workflows/profile-data-generator.yml'
      - 'fastlane/**'
      - 'Samples/TrendingMovies/**'

jobs:
  build-profile-data-generator-targets:
    name: Build app and UI test targets
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/ci-select-xcode.sh 13.4.1
      - name: Install SentryCli
        run: brew install getsentry/tools/sentry-cli
      - name: Cache Carthage dependencies
        id: trendingmovies-carthage-cache
        uses: actions/cache@v3
        with:
          path: ./Samples/TrendingMovies/Carthage/Build
          key: trendingmovies-carthage-cache-key-${{ hashFiles('Samples/TrendingMovies/Cartfile.resolved') }}
      - name: Install Carthage deps
        if: steps.trendingmovies-carthage-cache.cache-hit != 'true'
        run: cd Samples/TrendingMovies && carthage update --use-xcframeworks
      - run: fastlane build_profile_data_generator_ui_test
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
          FASTLANE_KEYCHAIN_PASSWORD: ${{ secrets.FASTLANE_KEYCHAIN_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
